config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles do
    resources :comments
    member do
      put 'like', to: 'articles#like'
      put 'unlike', to: 'articles#unlike'
    end
  end

  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :comments
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50}
  validates :description, presence: true, length: { minimum: 10, maximum: 1000}
  validates :user_id, presence: true
  is_impressionable
  acts_as_votable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy, :like, :unlike]
  before_action :require_user, except: [:index, :show, :like, :unlike]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :session_hash]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 6).order('created_at DESC')
    @users = User.all
    # @comment = Comment.find(:id)
    # @user = User.where(current_user != @article.user).take!
  end

  def new 
    @article = Article.new
  end

  def edit

  end

  
  def create
    # debugger
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
    @users = User.all
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end

  def like
    @article.liked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path}
      format.js { render layout:false}
    end
  end

  def unlike
    @article.unliked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path}
      format.js { render layout:false}
    end
  end


  private
  def set_article
    @article = Article.find(params[:id])
  end
  
  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin
    flash[:danger] = "You can only edit or delete your own articles"
    redirect_to root_path
    end
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row article" >
        <div class="thumbnail">
          <!-- <% @users.each do |user| %>
            <% if current_user != article.user && logged_in? %>
              <div class="favorites">
                <a href="#" >
                  <i class="glyphicon glyphicon-star-empty fav"></i>
                </a>
              </div>
              <% break %>
            <% end %>
          <% end %> -->
          <span class="data-id"><%= article.id %></span>
          <% if article.categories.any? %>
            <small><%= render article.categories %></small>
          <% end %>
          <h3><%= link_to article.title, article_path(article) %></h3>
          <p><%= truncate(article.description, length: 400) %></p>
          <div class="article-details">
            <div class="main">
              <small class="mb5">
                BY: <%= link_to article.user.username.upcase, user_path(article.user) %> |
                <!-- <%= article.user.username.upcase if article.user %> | -->
              </small>
              <small class="grey">
                <%= time_ago_in_words(article.created_at).upcase %> AGO,
              </small>
              <small class="grey">
                UPDATED: <%= time_ago_in_words(article.updated_at).upcase %> AGO
              </small> |
              <small class="grey">
                 <%= link_to article.comments.count, article_path(article)  %>
                <span class="glyphicon glyphicon-comment"></span>
              </small> |
              <small class="grey">
                  <%= article.impressionist_count  %>
                 <span class="glyphicon glyphicon-eye-open"></span>
               </small>
            </div>
            <div class="likes">
              <small class="likes">
                <% if logged_in? %>
                <% if current_user.liked? article %>
                  <%= link_to unlike_article_path(article), method: :put, class: "unlike_shot" do %>
                    <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                    <span class="vote_count"><%= article.get_likes.size %></span>
                  <% end %>
                <% else %>
                  <%= link_to like_article_path(article), method: :put, class: "like_shot" do %>
                    <span class="icon"><i class="fa fa-heart"></i></span>
                    <span class="vote_count"><%= article.get_likes.size %></span>
                  <% end %>
                  <% end %>
                <% else %> 
                  <%= link_to login_path, class: "like_shot" do %>
                    <span class="icon"><i class="fa fa-heart"></i></span>
                    <span class="vote_count"><%= article.get_likes.size %></span>
                  <% end %>
                <% end %>
              </small>
            </div>
          </div>

          <div class="caption">
            <% if logged_in? && (current_user == article.user || current_user.admin?) %>
              <div class="buttons">
                <%= link_to 'Edit', edit_article_path(article) %>
                <%= link_to 'Show', article_path(article) %>
                
                  <%= link_to 'Delete', article_path(article), method: :delete,
                  data:{confirm: "Are you sure?"} %>
                
              </div>
            <% end %>
          </div>
        </div>
    </div>
<% end %>

app/views/articles/_form.html.erb
<div class="container">
  <div class="form">
      <%= render 'shared/errors', obj: @article %>


    <%= form_for(@article, :html => {class: "", row: ""}) do |f| %>
      <div class="form-group">
        <%= f.label :title %> 
        <%= f.text_field :title, class:"form-control", placeholder: "Title of article", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.label :description %> 
        <%= f.text_area :description, class:"form-control", placeholder: "Body of article"%>
      </div>
      <div class="form-group">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
        <% end %>
      </div>
      <div class="btnTwo">
        <%= f.submit id: "form" %> 
        <%= link_to 'Back to the list', articles_path, class:"btn btn-primary ml20 fit" %> 
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<div>
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container cont-rel">
  
  <% if logged_in? %>
    <%= link_to "New Article", new_article_path, class: "btn btn-primary new" %>
  <% end %>
  <div align="center">
    <%= will_paginate @articles %>
  </div>
  <div class="newArticle" id="cardArticle">
    <%= render 'article', obj: @articles %>
  </div>
  <div align="center">
    <%= will_paginate @articles %>
  </div>
</div>

<script>
  // new addArticle();
</script>

app/views/articles/new.html.erb
<h1 class="center">Share your article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container" id="cardArticle"> 
  <div class="row article show">
      <div class="thumbnail">
          <!-- <% @users.each do |user| %>
          <% if current_user != @article.user && logged_in? %>
            <div class="favorites">
              <a href="#" >
                <i class="glyphicon glyphicon-star-empty fav"></i>
              </a>
            </div>
            <% break %>
          <% end %>
        <% end %> -->
        <span class="data-id"><%= @article.id %></span>
        <div class="is-two">
          <h3><%= @article.title %></h3>
          <div class="likes">
            <% if logged_in? %>
              <% if current_user.liked? @article %>
                <%= link_to unlike_article_path(@article), method: :put, class: "unlike_shot" do %>
                  <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                  <span class="vote_count"><%= pluralize(@article.get_likes.size, 'Like') %></span>
                <% end %>
              <% else %>
                <%= link_to like_article_path(@article), method: :put, class: "like_shot" do %>
                  <span class="icon"><i class="fa fa-heart"></i></span>
                  <span class="vote_count"><%= pluralize(@article.get_likes.size, 'Like') %></span>
                <% end %>
              <% end %>
            <% else %> 
              <%= link_to login_path, class: "like_shot" do %>
                <span class="icon"><i class="fa fa-heart"></i></span>
                <span class="vote_count"><%= pluralize(@article.get_likes.size, 'Like') %></span>
              <% end %>
            <% end %>
          </div>
        </div>
        <% if @article.user %>
          <ul class="">
            <div class="colum">
              <div class="right">
                <p><%= link_to gravatar_for(@article.user), user_path(@article.user) %></p>
                <p class="article-title">
                </p>
              </div>
              <div class="left">
                  <%= link_to@article.user.username, user_path(@article.user) %>
                  <p><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></p>
              </div>
            </div>
          </ul>
        <% end %>
        <div class="center">
          <%= simple_format(@article.description) %>
          <% if @article.categories.any? %>
            <small>Categories: <%= render @article.categories %></small>
          <% end %>
        </div>
        <div class="caption">
            <div class="columnBtn">
              <% if logged_in? && (current_user == @article.user || current_user.admin? ) %>
                <%= link_to 'Edit', edit_article_path(@article), class:"btn btn-primary ml20" %> 
                <%= link_to 'Delete', article_path(@article), class:"btn btn-primary ml20", method: :delete,
                  data:{confirm: "Are you sure?"} %>
              <% end %>
                <%= link_to 'View all articles', articles_path, class:"btn btn-primary ml20" %>
              </div>
        </div>
        <div class="panel panel-default widget">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-comment"></span>
                <h3 class="panel-title">Recent Comments</h3>
                <span class="label label-info">
                  <strong><%= @article.comments.count %></strong> |
                  <strong><%= pluralize( @article.impressionist_count ,'View') %></strong>
                </span>
            </div>
            <div class="panel-body">
              <ul class="list-group">
                <li class="list-group-item">
                  <%= render @article.comments %>
                </li>
              </ul>
              <div class="container">
                <h3>Leave a reply</h3>
                <% if logged_in? %>
                  <%= render 'comments/form' %>
                <% else %>
                  <small id="emailHelp" class="form-text text-muted">Log in to leave a comment.</small>
                  <%= link_to 'Sign in', login_path, class: "btn btn-primary w100" %>
                <% end %>
              </div>
                <!-- <a href="#" class="btn btn-primary btn-sm btn-block" role="button"><span class="glyphicon glyphicon-refresh"></span> More</a> -->
            </div>
          </div>
      </div>
  </div>
</div>

<script>
    // new addArticle();
  </script>