config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles do
    resources :comments
    member do
      put 'like', to: 'articles#like'
      put 'unlike', to: 'articles#unlike'
    end
  end

  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 30}
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def new
    @category =Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @users = User.all
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_for(@category, :html => {class: "", row: ""}) do |f| %>
    <div class="form-group">
      <%= f.label :category %> 
      <%= f.text_field :name, class:"form-control", placeholder: "Enter category name", autofocus: true %>
    </div>
    <div class="btnTwo">
      <%= f.submit id: "form" %> 
      <%= link_to 'Back to the list', articles_path, class:"btn btn-primary ml20 fit" %> 
    </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class="form">
    <h2>Edit Category Name</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <h2 class="center mt15">Listing all Categories</h2>
  <div class="form">
    <% if logged_in? and current_user.admin? %>
      <%= link_to "New Category", new_category_path, class: "btn btn-primary new" %>
    <% end %>
    <div align="center">
      <%= will_paginate %>
    </div>
    <% @categories.each do |category| %>
      <div class="category">
        <div class="content">
          <p><%= link_to "#{category.name}", category_path(category) %></p>
          <small><%= pluralize(category.articles.count, "article") %> </small>
        </div>
      </div>
    <% end %>
    <div align="center">
      <%= will_paginate %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<h2>Create a new Category</h2>


<%= render 'shared/errors', obj: @category %>
  <%= form_for(@category, :html => {class: "", row: ""}) do |f| %>
      <div class="form-group">
        <%= f.label :category %> 
        <%= f.text_field :name, class:"form-control", placeholder: "Enter category name", autofocus: true %>
      </div>
      <div class="btnTwo">
        <%= f.submit id: "form" %> 
        <%= link_to 'Back to the list', articles_path, class:"btn btn-primary ml20 fit" %> 
      </div>
  <% end %>

app/views/categories/show.html.erb
<div class="container">
  <h2 align="center"><%= "Category: " + @category.name %></h4>
    <% if logged_in? and current_user.admin? %>
      <%= link_to "Edit", edit_category_path(@category), class: "btn btn-primary new" %>
    <% end %>
    <div align="center">
      <%= will_paginate @category_articles %>
    </div>
    <div class="newArticle" id="cardArticle">
      <%= render 'articles/article', obj: @category_articles %>
    </div>
    <div align="center">
      <%= will_paginate @category_articles %>
    </div>
  </div>
  
  <!-- <script>
    new addArticle();
  </script> -->