config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles do
    resources :comments
    member do
      put 'like', to: 'articles#like'
      put 'unlike', to: 'articles#unlike'
    end
  end

  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<div class="u-cf empty"></div>
<div class="footer">
    <div class="logo">
      <p>Copyright &copy; 2019 Blog &checkmark; Yair Fernando</p>
    </div>
</div>

app/views/layouts/_hero.html.erb
<% if !logged_in? %>
<div class="alert alert-info alert-login" role="alert">
  <p>
    Do you want to write awesome articles? <span class=""> Join now.!!!</span>
  </p>  
    <%= link_to "Login", login_path, class: "" %> 
</div>
<% end %>

app/views/layouts/_messages.html.erb
<div class="container">
  <% if flash.any? %>
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}"%>' id="msg" alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  <% end %>
</div>

<script>
  // new deleteErrors;
</script>

app/views/layouts/_navigation.html.erb
<div class="navigation">
    <nav class="navbar navbar-default navbar-fixed-top navbar-shrink">
        <!-- <%= render 'layouts/hero' %> -->
        <div class="navegacion">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "APP Blog", root_path, class: "navbar-brand page-scroll", id: "logo" %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden active">
                        <a href="#page-top"></a>
                    </li>
                    <li class="">
                      <%= link_to "Articles", articles_path, class: "page-scroll" %>
                    </li>
                    <!-- <li class="">
                      <%= link_to 'About', about_path, class: "page-scroll"  %>
                    </li> -->
                    <li class="">
                      <%= link_to 'Users', users_path, class: "page-scroll"  %>
                    </li>
                    <% if logged_in? %>
                      <!-- <li class="">
                        <%= link_to 'Log Out', logout_path, method: :delete, class: "page-scroll"  %>
                      </li> -->
                      <li class="submenu">
                        <!-- <a href="#" id="img-article" class="page-scroll">Favorites</a> -->
                        <div id="articles">
                          <table class="u-full-width" id="list-articles">
                            <thead>
                              <tr>
                                <th>Title</th>
                                <th>Description</th>
                                <th></th>
                              </tr>
                            </thead>
                            <tbody></tbody>
                          </table>
                          <a href="#" id="clean-articles" class="u-full-width ground">Clean Articles</a>
                        </div>
                      </li>
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle page-scroll" 
                            data-toggle="dropdown" 
                            role="button" aria-haspopup="true" 
                            aria-expanded="false">Categories
                          </a>
                          <ul class="dropdown-menu dropProfile" id="displayProfile">
                            <li><%= link_to "All Categories", categories_path %> </li>
                            <% Category.all.each do |category| %>
                              <li><%= link_to "#{category.name}", category_path(category) %></li>
                            <% end %>
                            <% if logged_in? and current_user.admin? %>
                            <li role="separator" class="divider"></li>
                            <li><%= link_to "Create New Category", new_category_path %> </li>
                            <% end %>
                          </ul>
                        </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle page-scroll" 
                          data-toggle="dropdown" 
                          role="button" aria-haspopup="true" 
                          aria-expanded="false">Profile <%= "Admin" if current_user.admin? %>
                          
                        </a>
                        <ul class="dropdown-menu dropProfile" id="displayProfile">
                          <li><%= link_to "Edit profile", edit_user_path(current_user) %> </li>
                          <li><%= link_to "View profile", user_path(current_user) %> </li>
                          <li role="separator" class="divider"></li>
                          <li class="">
                            <%= link_to 'Log Out', logout_path, method: :delete, class: "page-scroll"  %>
                          </li>
                        </ul>
                      </li>
                      <% else %>
                      <li>
                        <%= link_to 'Log in', login_path, class: "page-scroll"  %>
                      </li>
                      <li>
                        <%= link_to 'Sign up', signup_path, class: "page-scroll"  %>
                      </li>
                    <%end%>
                   
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
</div>

<script>
  // new deleteArticle()
  // new cleanArticles()
  // new loadLocalStorage()
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,400" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Big+Shoulders+Display|Lato:300,400|Staatliches&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <!-- <%= debug(params) if Rails.env.development? %> -->
  </body>
</html>